### ISSUE TITLE
Enhancement doesn't affect Watermelon yield

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#178]
From client:
https://pollinator-modeling-app.azavea.com/project/38/scenario/88

>I was following up with Eric on a project where I created different scenarios. The outputs look strange. Eric thought it might be a bug and asked I pass it on to Matt McFarland. Can you send it on to him? I don't have his email.

>You can find the project here. I thought it was a result of how I drew the enhancement (e.g. in the process of outlining the area of interest, at some point part or all of the blueberry and watermelon fields were covered by the enhancement), but I'm not sure why it only causes blueberry yield to drop dramatically.

Perhaps the model is working as intended, and these enhancements are not meant to affect watermelon yield. But it does look odd that watermelons show now difference across different sizes of enhancements:
![screen shot 2017-04-20 at 11 09 20 am](https://cloud.githubusercontent.com/assets/12868342/25237883/d7686f38-25b9-11e7-9707-9f962663f301.png)

**Comment by arottersman** [comment]
Tried to recreate the 7 acre wild flower results, and couldn't.

Here is their's with no blueberry yield:
<img width="960" alt="screen shot 2017-04-21 at 9 16 58 am" src="https://cloud.githubusercontent.com/assets/7633670/25279454/866bc0f6-2674-11e7-82ec-27ef782e0e07.png">

Here is mine:
<img width="960" alt="screen shot 2017-04-21 at 9 33 29 am" src="https://cloud.githubusercontent.com/assets/7633670/25279780/9ccd601a-2675-11e7-8fa3-111fe68fabe5.png">

**Comment by arottersman** [comment]
While working on another card, I noticed that if a current conditions landcover overlaps another ever so slightly, the overlapped landcover doesn't return results:

<img width="960" alt="screen shot 2017-04-25 at 3 36 29 pm" src="https://cloud.githubusercontent.com/assets/7633670/25404386/bac837d8-29cd-11e7-8f4a-d9a197493030.png">

**Comment by arottersman** [comment]
The heart of this issue is we are able to draw geometries at a much finer resolution than the 30m CDL raster.

Here is a contrived example:

We cover a small AoI with blueberry landcover:
![screen shot 2017-04-26 at 10 16 10 am](https://cloud.githubusercontent.com/assets/7633670/25439283/092366ea-2a6a-11e7-9817-b7d9a1fb97c6.png)

We draw another modification around it (in this case wildflower):
![screen shot 2017-04-26 at 10 15 50 am](https://cloud.githubusercontent.com/assets/7633670/25439280/05e036e8-2a6a-11e7-88b9-dcffc88eb290.png)

We can still see the blueberry landcover on the map, and yet its yield has dropped to 0. The yield drops to 0 because the landcover geometry is masked onto the raster wherever the geometry intersects with a cell. As far as the geoprocessing is concerned our original blueberry AoI was this:
![screen shot 2017-04-26 at 10 16 10 am](https://cloud.githubusercontent.com/assets/7633670/25447592/c37e37e0-2a83-11e7-9c65-2aa52d2c2d82.png)

And our AoI with wildflower was this:
![screen shot 2017-04-26 at 10 15 50 am](https://cloud.githubusercontent.com/assets/7633670/25447603/cf154ae4-2a83-11e7-8843-b9ec1cdbb560.png)

We bake modifications into the raster in the order they are drawn, so wildflower entirely overwrites the blueberry cell, erasing the blueberry yield.

When applying the modifications to the raster [we write values for cells that the geom intersects, however much](https://github.com/project-icp/bee-pollinator-app/blob/develop/src/icp/pollinator/src/pollinator/raster_ops/__init__.py#L59), ie the [`geom_mask` param `all_touched=True`](https://github.com/mapbox/rasterio/blob/19e1de74861e65ffc15489ea0c9e7d122a8e8fe9/rasterio/features.py#L38). We would still have a problem if we were to set `all_touched` to `False`, and only modify cells for which a geom intersected a cell's centroid. Consider for example a case where the shape doesn't intersect any of the cells' centroids, and therefore doesn't exist on the modified raster and yield output:
![screen shot 2017-04-26 at 10 16 10 am](https://cloud.githubusercontent.com/assets/7633670/25448623/15b0ad24-2a87-11e7-8374-2952187fd5cc.png)


After discussing with @mmcfarland, it seems there's not a true solution in lieu of a way to force users to draw "snapped" to the raster cells. Thankfully we've already at some point told the client the low resolution CDL would cause issues.

One possible thing we could do in response to is, detect on the front end if there's a landcover mod that's not entirely covered up, but still has 0 yield. Then warn the user about the results accordingly.

**Comment by mmcfarland** [comment]
After discussing this with ICP, we'll be addressing this largely via help text.  Thanks for the helpful visuals @arottersman.
