### ISSUE TITLE
Beekeepers app should be avail at the same base route

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#309]
Get the homepage and the beekeeper app urls on the same url scheme. Currently the homepage is at `/?beekeepers` and the rest of the beekeepers Django app is at `/beekeepers/`). [The ADR](https://github.com/project-icp/bee-pollinator-app/blob/develop/doc/phase-2/000_project_architecture_adr.md#consequences) discussed something like the latter.

**Comment by rajadain** [comment]
I thought that `/beekeepers/` would house the API, but the front-end would be available at the root. Since they're on the same domain, we don't need to worry about CSRF issues. The `/?beekeepers` route is only for development, in production it'll be `app.beekeepers.url` or something like that, i.e. at the root of the domain.

**Comment by fungjj92** [comment]
Oh hm, true. In prod & staging we'll eventually differentiate by the host that's making the request than this query string. Closing, I'll bring in another ~1 point card instead.
