### ISSUE TITLE
Update CDL tiled layer to 2017 version

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#371]
Generate a new tile set for the CDL visual tiles based on the 2017 release based on the processed raster produced in #407

* [x] Generate tiles at same zoom levels as current version
* [x] Upload to tile bucket under name with the year included
* [x] In the beekeeper app, use as the endpoint for #367

**Comment by rajadain** [comment]
# Ingest Process

This ingest was performed successfully using two techniques: once with GeoTrellis, and once with GDAL. The GDAL ingest was done as an experiment since we kept running in to problems with GeoTrellis. Here is an overview of the process:

## GeoTrellis Ingest

This used the [`civic-apps-etl`][ca-etl] repo, as have other ingests in the past, as well as the steps outlined in [this blog post][gt-ingest-blog].

The first experiment was done locally, by cloning the repo and adding a branch for doing the work [`tt/beekeepers-cdl-ingest-paint`][ca-etl-branch]. In this branch, I added a class to take a GeoTIFF, generate a temporary RDD, and then generate tiles from the RDD.

This was run locally, with the expectation that the tiles could be uploaded to S3 from my local machine. Unfortunately, my machine ran out of space before the operation could complete.

The next step was creating an EC2 instance and running it there. As I thought the operation was CPU bound, I decided to get a `c4.2xlarge` instance and run the operation there. I gave it a 32GB SSD and then ran the ingest there, but it also ran out of space.

At that point I reached out to @hectcastro for assistance who helped setup an `m5d.2xlarge` instance for ingests. We went for the `m5` because it is a general purpose machine and is a more recent generation, and with `m5d` because it comes with special high performance IO in the form of an NVME drive whose contents are flushed on shutdown.

I checked out the repo on the `m5d.2xlarge` instance and downloaded the original GeoTIFF from S3, and then ran GeoTrellis on that. I ensured that Spark was configured to use the NVME drive for its temp storage as well, so we would get the maximum performance. The tiles were finally generated, and uploaded to S3 as `cdl-reclass-2017`.

## GDAL Ingest

While we were dealing with various GeoTrellis issues, after a conversation with @rossbernet I investigated GDAL ingests. @mmcfarland had mentioned there being `gdal2tiles.py` which I tried out. The steps there were to first reproject the GeoTIFF into Web Mercator:

```
$ gdalwarp -multi -co NUM_THREADS=ALL_CPUS -wo NUM_THREADS=ALL_CPUS -oo NUM_THREADS=ALL_CPUS -doo NUM_THREADS=ALL_CPUS -co TILED=YES -co COMPRESS=DEFLATE -t_srs EPSG:3857 2017_cdl_reclass_lzw_5070.tif 2017_cdl_reclass_lzw_3857.tif
```

All the `NUM_THREADS=ALL_CPUS` options are necessary to make it run on all threads. Once I had the reprojected GeoTIFF, I had to make a VRT, required for `gdal2tiles.py` (since the GeoTIFF only has RGB values, but PNG tiles also need alpha):

```
$ gdal_translate -of vrt -expand rgba 2017_cdl_reclass_lzw_3857.tif 2017_cdl_reclass_lzw_3857.vrt
```

At this point, we were ready to generate the tiles, so I ran:

```
$ gdal2tiles.py -z 0-13 -r near geotiff/2017_cdl_reclass_lzw_3857.vrt tiles/
```

where `-z 0-13` specifies the zoom levels, and `-r near` sets the resampling method as Nearest Neighbor (which is the recommended method when dealing with categorical data). Unfortunately, this generated a set of TMS tiles, instead of XYZ tiles which we regularly use.

After asking for help with this, @chitchens recommended [this repo][gdal2tiles] which was a fork of `gdal2tiles` with the addition of XYZ support. By using that, I was able to generate the right XYZ tiles:

```
$ ./lib/gdal2tiles.py -z 0-13 -r near -x --processes=8 geotiff/2017_cdl_reclass_lzw_3857.vrt tiles/
```

where `-x` specifies XYZ tiles, and `--processes=8` sets the use of multiple processes, useful since I was using an `m5d.2xlarge` instance on EC2.

Unfortunately, when I first ran this on the instance created for the GeoTrellis ingest, it quickly ran out of space as it only had 8GB of EBS storage, and I couldn't figure out how to get GDAL to use the NVME drive. Thus, I made a new `m5.2xlarge` instance, copied over all the work that had been done so far, and ran `gdal2tiles.py` again with `-e` which specifies reusing existing files, thus it skips those that have been made.

This set was finally uploaded as `cdl-reclass-2017-gdal`.

## Comparison

The reason I went with both is because the GeoTrellis ingest seems to have some rasterization artifacts causing the pixels to appear not-square. For example, this is a screenshot of the GDAL layer:

![image](https://user-images.githubusercontent.com/1430060/51502093-79fc5c00-1da2-11e9-9f0e-49df4b37e511.png)

And this is one from the GeoTrellis layer:

![image](https://user-images.githubusercontent.com/1430060/51502099-7f59a680-1da2-11e9-8a3f-2df1c0743964.png)

As can be seen, the GDAL layer has clearer boundaries, and maintains the "pixelness" of the source data. The GeoTrellis version seems to be making it conform to a vertical grid and has a number of aberrations on the edges.

Here's a GIF that shows the subtle differences between them:

![2019-01-18 17 40 57](https://user-images.githubusercontent.com/1430060/51502155-c778c900-1da2-11e9-9a9a-5617bc645995.gif)

Both sets of tiles are on S3, and we can decide which one is better / should be used.

[ca-etl]: https://github.com/azavea/civic-apps-etl
[ca-etl-branch]: https://github.com/azavea/civic-apps-etl/tree/tt/beekeepers-cdl-ingest-paint
[gdal2tiles]: https://github.com/Luqqk/gdal2tiles
[gt-ingest-blog]: https://www.azavea.com/blog/2018/08/06/generating-pyramided-tiles-from-a-geotiff-using-geotrellis/

**Comment by rossbernet** [comment]
@rajadain This is very helpful. Thanks for the detailed writeup. Of course I'm not happy to hear that the GeoTrellis route provided some frustration, but it is great to know about them and understand the alternatives better.

I was just speaking with @moradology about this. He shares concerns that this was difficult. But that he's not surprised to see some differences in the GT result because you did reproject it afterall - so we should expect to see some artifacts. But perhaps we are missing something? Does the resulting raster layer from the GDAL route look more like you expected?

**Comment by rajadain** [comment]
Both ingests were done from the same source TIFF, which was in EPSG:5070, and the output for both is in EPSG:3857. In GeoTrellis, the reprojection was done as part of the tiling, as shown [in this file](https://github.com/azavea/civic-apps-etl/blob/tt/beekeepers-cdl-ingest-paint/mmw-ingest/src/main/scala/PaintFromGeoTIFFLocal.scala). In GDAL, the reprojection was done via `gdalwarp`. In both cases, `NearestNeighbor` was specified as the resampling method.

Since the source data consists of 30m pixels, I expect the generated tiles to have that "square" appearance when zoomed in. In the GDAL output, that "square pixel" is preserved, but in GeoTrellis it is jagged.

One thing we could try to experiment further is to tile, using GeoTrellis, a TIFF that has been pre-reprojected with `gdalwarp`, so GT does only the tiling and not the reprojection, and see if we still see the artifacts.

I can provide you with the source TIFFs if the team would like to experiment on this.

**Comment by notthatbreezy** [comment]
Thanks for writing this up - this is really interesting. I'd be interested in the source TIFFs if it's possible - I'd like to convert them to COGs and add them in RF and see if we can approximate the visualization you're using now.
