### ISSUE TITLE
Text Updates

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#433]
Update text throughout the app based on what the clients provide.

**Comment by fungjj92** [comment]
Is the "registration pop-up" the modal that opens when you click this button?
![screen shot 2019-01-29 at 5 05 06 pm](https://user-images.githubusercontent.com/10568752/51943667-17c9d980-23e8-11e9-80c1-933989a8a7e3.png)

**Comment by fungjj92** [comment]
The proposed -- "Search bar should read "Zoom to your location" would indicate that the search zooms. Currently, the geolocation search maintains the zoom level while displaying the selected location.

**Comment by fungjj92** [comment]
The registration workflow backend are the exact same between the two apps (Bee Pollinator and Beescape). This includes things like registration email copy, forget password confirmation, activation link confirmation page. Can we get copy that is generic and friendly to make sense within the context of both? It would otherwise be a heavy lift 🤔
