### ISSUE TITLE
Wipe out Jenkins build workspaces fully before running a build

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#541]
### Overview
Jenkins builds fail universally for all Jenkins Bees projects unless the workspace is wiped out before the build. We have been manually wiping the workspaces but that has been failure-prone. Jenkins has a "Delete workspace before build starts" flag that has recently been turned on for all Bees projects, which should help alleviate this problem for now. The story complicates.

> One complication with clearing the workspace is that usually that doesn’t include destroying the associated workspace VMs. Since Vagrant tracks metadata about the VMs it manages in .vagrant, clearing the workspace could lead to an increasing number of dangling VM references.
-HMC

The problem is deeper than wiping the workspace -- builds shouldn't be failing in the first place but this work is not budgeted to investigate. A cheaper and direct solution would be to add this pre-build script that runs before any Bees project:
> vagrant destroy -f  from the root of the workspace directory, as the jenkins user.
-HMC

**Comment by hectcastro** [comment]
In the process of initializing a release branch today, I disabled the workspace deletion functionality for all project builds and replaced it with an explicit `vagrant destroy -f` post-build task. The Packer and staging deployment builds do not have a post-build task because they don't utilize VMs to do their work.

- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-release/39/
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-release/40/

This approach has similar downsides to deleting the workspace in that every new build needs to provision the Vagrant environment from scratch (time consuming), but it does so by maintaining the relationship between Vagrant and the VirtualBox VM lifecycle.

**Comment by fungjj92** [comment]
Thanks @hectcastro , I'll consider this issue "done" then.
