### ISSUE TITLE
Edit colony questions in Spring Survey

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#559]
- [x]  Add a line that displays the number of colonies the user entered for that apiary in the Fall survey

- [x]  Implement validation logic that prevents the user from entering more colonies on the Spring survey than were on the Fall survey

- [x]  Add the question - “How many new colonies did you add to this apiary over the winter?”

**Comment by rajadain** [comment]
On one hand it says that users should not be allowed to enter a value for Number of Colonies that is greater than that of the Fall. On the other hand, it says to add a field to count how many new colonies were added.

Let's say they had 3 in the Fall, none of which perished over the winter, and also they added 2 more, for current total of 5. If we do implement logic to prevent them from specifying a Number of Colonies greater than that in the Fall, they cannot correctly report that they now have 5 total colonies.

Can we consider changing the questions to be:

* How many of the colonies you entered in the Fall survey remain?
* How many new colonies have you added since the Fall survey?

And then have an auto-calculated total, using the logic:

```
total = colonies_remain + colonies_gained
```

**Comment by dboyer** [comment]
Proposed wireframe from the client for this set of questions:

![Screen Shot 2020-02-17 at 1 35 06 PM](https://user-images.githubusercontent.com/516764/74678898-57499c00-518a-11ea-8b10-5f29831a4ef4.png)

**Comment by rajadain** [comment]
Just had a call with the clients. We should do the following:

1. Add a field to the April Survey called `num_new_colonies` (allow nulls, default 0)
2. Remove the "How many colonies are in this apiary?" question from the April Survey
3. Add a question to the April Survey:
    > You had **XX** colonies in November. How many of those currently remain?
    The answer to the above should be validated to not be more than that in November. This field should default to empty, and must be a required field.
4. Add a question to the April Survey:
    > How many new colonies did you add over the winter, since the November survey?
    This field should default to 0, and must be a required field.
5. Fill the value of (4) in `num_new_colonies`, and the value of (3) + (4) in `num_colonies`
6. When opening an existing April Survey, we should fill out the answer to (3) as `num_colonies - num_new_colonies`, and fill out (4) as `num_new_colonies`. If `num_new_colonies` is NULL, we should treat it as 0 in the front-end for the above calculation.
